name: Generate Content From Wiki

on:
  push:
    branches:
      - stable
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    
    - name: Obtain Wiki Files
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: wiki
        
    - name: Create Index JSON
      run: |
        cd wiki
        ls -a
        tree -J > index.json
        ls -a
