name: Sync Wiki

on:
  push:
    branches:
      - stable

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
    - name: Obtain Wiki Files
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: markdown
        
    - name: Create Index JSON
      run: |
        ls -a markdown
        tree -J markdown > index.json
        ls -a markdown
