name: Sync Wiki

on:
  push:
    branches:
      - stable

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
    - name: Obtain Wiki Files
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: markdown
        
    - name: Copy To Repository
      run: |
        cd markdown
        echo "Debug..."
        ls -a
        
    - name: Generate Index
      uses: jsdaniell/create-json@v1.2.1
      with:
        name: "index.json"
        dir: "projects/"
        json: '["foo"]'
