name: Sync Wiki

on:
  push:
    branches:
      - stable
      
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync Wiki
      uses: jamesgeorge007/wiki-sync-action@v1
      with:
        repo: "georgewilkins/project-blog"
        directory: "projects"
        token: ${{ secrets.GITHUB_TOKEN }}
