name: Sync Wiki

on:
  push:
    branches:
      - stable

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
    - name: Obtain Wiki Files
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: markdown
        
    - name: Copy To Repository
      run: |
        cd markdown
        echo "Debug..."
        ls -a
